// integrations/harbor/tasks/todo-angular/steps/follow-up/solution/app/src/app/app.ts
import { Component, computed, signal } from '@angular/core';

type Priority = 'low' | 'normal' | 'high';

interface Task {
  id: number;
  text: string;
  done: boolean;
  priority: Priority;
  createdAt: string;
}

const RANK: Record<Priority, number> = { high: 0, normal: 1, low: 2 };
const LABEL: Record<Priority, string> = { high: 'High', normal: 'Normal', low: 'Low' };

@Component({
  selector: 'app-root',
  template: `
    <main class="shell">
      <header class="head">
        <h1>To-do</h1>
        @if (tasks().length) {
          <p class="count">{{ remaining() }} of {{ tasks().length }} left</p>
        }
      </header>

      <form class="add" (submit)="add($event)">
        <label for="new-task" class="visually-hidden">New task</label>
        <input
          id="new-task"
          type="text"
          placeholder="What needs doing?"
          autocomplete="off"
          maxlength="500"
          [value]="draft()"
          (input)="draft.set($any($event.target).value)"
        />
        <label for="new-priority" class="visually-hidden">Priority</label>
        <select
          id="new-priority"
          title="Priority"
          [value]="priority()"
          (change)="priority.set($any($event.target).value)"
        >
          <option value="low">Low</option>
          <option value="normal">Normal</option>
          <option value="high">High</option>
        </select>
        <button type="submit" class="primary" [disabled]="!draft().trim() || adding()">Add</button>
      </form>

      @if (error()) {
        <p class="error" role="alert">{{ error() }}</p>
      }

      <ul class="list" aria-label="Tasks">
        @for (task of sorted(); track task.id) {
          <li class="item" [class.done]="task.done">
            <input
              type="checkbox"
              [id]="'task-' + task.id"
              [checked]="task.done"
              (change)="toggle(task, $any($event.target).checked)"
            />
            <label [for]="'task-' + task.id">{{ task.text }}</label>
            <span class="badge" [class]="'badge badge-' + task.priority">{{ label(task.priority) }}</span>
            <button
              type="button"
              class="delete"
              [attr.aria-label]="'Delete ' + task.text"
              [title]="'Delete ' + task.text"
              (click)="remove(task)"
            >
              <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true">
                <path d="M6 6l12 12M18 6L6 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" fill="none" />
              </svg>
            </button>
          </li>
        }
      </ul>

      @if (loaded() && !tasks().length) {
        <div class="empty">
          <span aria-hidden="true">📝</span>
          <p>No tasks yet. Add your first one above.</p>
        </div>
      }
    </main>
  `,
})
export class App {
  protected readonly tasks = signal<Task[]>([]);
  protected readonly draft = signal('');
  protected readonly priority = signal<Priority>('normal');
  protected readonly adding = signal(false);
  protected readonly loaded = signal(false);
  protected readonly error = signal('');
  protected readonly remaining = computed(() => this.tasks().filter((t) => !t.done).length);
  protected readonly sorted = computed(() =>
    [...this.tasks()].sort((a, b) => RANK[a.priority] - RANK[b.priority] || a.id - b.id)
  );

  constructor() {
    this.load();
  }

  protected label(p: Priority): string {
    return LABEL[p] ?? 'Normal';
  }

  private async load() {
    try {
      const res = await fetch('/api/tasks');
      if (!res.ok) throw new Error();
      this.tasks.set(await res.json());
      this.error.set('');
    } catch {
      this.error.set('Could not load tasks.');
    } finally {
      this.loaded.set(true);
    }
  }

  protected async add(event: Event) {
    event.preventDefault();
    const text = this.draft().trim();
    if (!text || this.adding()) return;
    this.adding.set(true);
    try {
      const res = await fetch('/api/tasks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, priority: this.priority() }),
      });
      if (!res.ok) throw new Error();
      const task: Task = await res.json();
      this.tasks.update((list) => [...list, task]);
      this.draft.set('');
      this.error.set('');
    } catch {
      this.error.set('Could not add the task.');
    } finally {
      this.adding.set(false);
    }
  }

  protected async toggle(task: Task, done: boolean) {
    this.tasks.update((list) => list.map((t) => (t.id === task.id ? { ...t, done } : t)));
    try {
      const res = await fetch(`/api/tasks/${task.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ done }),
      });
      if (!res.ok) throw new Error();
      this.error.set('');
    } catch {
      this.tasks.update((list) => list.map((t) => (t.id === task.id ? { ...t, done: !done } : t)));
      this.error.set('Could not update the task.');
    }
  }

  protected async remove(task: Task) {
    const previous = this.tasks();
    this.tasks.update((list) => list.filter((t) => t.id !== task.id));
    try {
      const res = await fetch(`/api/tasks/${task.id}`, { method: 'DELETE' });
      if (!res.ok && res.status !== 404) throw new Error();
      this.error.set('');
    } catch {
      this.tasks.set(previous);
      this.error.set('Could not delete the task.');
    }
  }
}

// integrations/harbor/tasks/todo-nuxt/steps/follow-up/solution/app/app/app.vue
<script setup>
useHead({ title: 'To-do' });

const PRIORITY_RANK = { high: 2, normal: 1, low: 0 };
const PRIORITY_LABEL = { high: 'High', normal: 'Normal', low: 'Low' };

const { data: tasks, error: loadError } = await useFetch('/api/tasks', { default: () => [] });

const newText = ref('');
const newPriority = ref('normal');
const adding = ref(false);
const errorMsg = ref('');
const input = ref(null);

const sortedTasks = computed(() =>
  [...tasks.value].sort(
    (a, b) => PRIORITY_RANK[b.priority] - PRIORITY_RANK[a.priority] || a.id - b.id
  )
);

const remaining = computed(() => tasks.value.filter((t) => !t.done).length);

function fail(err, fallback) {
  errorMsg.value = err?.data?.statusMessage || err?.statusMessage || fallback;
}

async function addTask() {
  const text = newText.value.trim();
  if (!text || adding.value) return;
  adding.value = true;
  errorMsg.value = '';
  try {
    const task = await $fetch('/api/tasks', {
      method: 'POST',
      body: { text, priority: newPriority.value },
    });
    tasks.value = [...tasks.value, task];
    newText.value = '';
  } catch (err) {
    fail(err, 'Could not add the task.');
  } finally {
    adding.value = false;
    input.value?.focus();
  }
}

async function toggle(task) {
  const done = !task.done;
  task.done = done;
  errorMsg.value = '';
  try {
    await $fetch(`/api/tasks/${task.id}`, { method: 'PATCH', body: { done } });
  } catch (err) {
    task.done = !done;
    fail(err, 'Could not update the task.');
  }
}

async function removeTask(task) {
  errorMsg.value = '';
  const before = tasks.value;
  tasks.value = before.filter((t) => t.id !== task.id);
  try {
    await $fetch(`/api/tasks/${task.id}`, { method: 'DELETE' });
  } catch (err) {
    tasks.value = before;
    fail(err, 'Could not delete the task.');
  }
}
</script>

<template>
  <main class="wrap">
    <header class="head">
      <h1>To-do</h1>
      <p v-if="tasks.length" class="count">
        {{ remaining }} of {{ tasks.length }} left
      </p>
    </header>

    <form class="add" @submit.prevent="addTask">
      <div class="field field-text">
        <label for="new-task" class="field-label">New task</label>
        <input
          id="new-task"
          ref="input"
          v-model="newText"
          type="text"
          maxlength="500"
          placeholder="What needs doing?"
          autocomplete="off"
        />
      </div>
      <div class="field field-priority">
        <label for="new-priority" class="field-label">Priority</label>
        <select id="new-priority" v-model="newPriority">
          <option value="low">Low</option>
          <option value="normal">Normal</option>
          <option value="high">High</option>
        </select>
      </div>
      <button type="submit" class="btn-primary" :disabled="adding">Add</button>
    </form>

    <p v-if="errorMsg || loadError" class="error" role="alert">
      {{ errorMsg || 'Could not load tasks.' }}
    </p>

    <ul v-if="tasks.length" class="list" aria-label="Tasks">
      <li v-for="task in sortedTasks" :key="task.id" class="item" :class="{ done: task.done }">
        <label class="check">
          <input type="checkbox" :checked="task.done" @change="toggle(task)" />
          <span class="text">{{ task.text }}</span>
        </label>
        <span class="badge" :class="`badge-${task.priority}`">
          {{ PRIORITY_LABEL[task.priority] }}
        </span>
        <button
          type="button"
          class="btn-delete"
          :aria-label="`Delete ${task.text}`"
          :title="`Delete ${task.text}`"
          @click="removeTask(task)"
        >
          <svg viewBox="0 0 24 24" width="18" height="18" aria-hidden="true">
            <path
              d="M4 7h16M10 11v6M14 11v6M6 7l1 12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2l1-12M9 7V4h6v3"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
            />
          </svg>
        </button>
      </li>
    </ul>
    <section v-else class="empty" aria-label="Tasks">
      <div class="empty-icon" aria-hidden="true">📝</div>
      <p>No tasks yet. Add your first one above.</p>
    </section>
  </main>
</template>
