// integrations/harbor/tasks/tip-calculator-nuxt/steps/follow-up/solution/app/app/app.vue
<script setup>
useHead({
  title: 'Tip Calculator',
  htmlAttrs: { lang: 'en' },
});

const bill = ref('');
const tipPercent = ref(15);
const people = ref(1);
const roundUp = ref(false);

const presets = [10, 15, 18, 20, 25];

function toNumber(v) {
  if (v === '' || v === null || v === undefined) return 0;
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
}

const billValue = computed(() => Math.max(0, toNumber(bill.value)));
const tipValue = computed(() => Math.max(0, toNumber(tipPercent.value)));
const peopleValue = computed(() => {
  const n = Math.floor(toNumber(people.value));
  return n >= 1 ? n : 1;
});

const errors = computed(() => {
  const list = [];
  if (toNumber(bill.value) < 0) list.push('Bill amount can’t be negative.');
  if (toNumber(tipPercent.value) < 0) list.push('Tip percent can’t be negative.');
  if (people.value !== '' && toNumber(people.value) < 1) list.push('People must be at least 1.');
  return list;
});

// Work in cents to avoid floating-point surprises (e.g. 23.000000001 rounding up to 24).
const rawTotalCents = computed(() =>
  Math.round((billValue.value + (billValue.value * tipValue.value) / 100) * 100)
);
const totalCents = computed(() =>
  roundUp.value ? Math.ceil(rawTotalCents.value / 100) * 100 : rawTotalCents.value
);

const total = computed(() => totalCents.value / 100);
const tip = computed(() => Math.max(0, total.value - billValue.value));
const perPerson = computed(() => total.value / peopleValue.value);
const effectivePercent = computed(() =>
  billValue.value > 0 ? (tip.value / billValue.value) * 100 : tipValue.value
);

const fmt = (n) => '$' + n.toFixed(2);

function changePeople(delta) {
  people.value = Math.max(1, peopleValue.value + delta);
}

function reset() {
  bill.value = '';
  tipPercent.value = 15;
  people.value = 1;
  roundUp.value = false;
}
</script>

<template>
  <main class="page">
    <section class="card" aria-labelledby="title">
      <header class="head">
        <span class="logo" aria-hidden="true">🧾</span>
        <div>
          <h1 id="title">Tip Calculator</h1>
          <p class="sub">Split the bill fairly, instantly.</p>
        </div>
      </header>

      <div class="layout">
        <form class="inputs" @submit.prevent>
          <div class="field">
            <label for="bill">Bill amount</label>
            <div class="affix">
              <span class="prefix" aria-hidden="true">$</span>
              <input
                id="bill"
                v-model="bill"
                type="number"
                inputmode="decimal"
                min="0"
                step="0.01"
                placeholder="0.00"
                autocomplete="off"
              />
            </div>
          </div>

          <div class="field">
            <label for="tip">Tip percent</label>
            <div class="affix">
              <input
                id="tip"
                v-model="tipPercent"
                type="number"
                inputmode="decimal"
                min="0"
                step="1"
                placeholder="15"
                autocomplete="off"
              />
              <span class="suffix" aria-hidden="true">%</span>
            </div>
            <div class="presets" role="group" aria-label="Quick tip percentages">
              <button
                v-for="p in presets"
                :key="p"
                type="button"
                class="chip"
                :aria-pressed="toNumber(tipPercent) === p"
                @click="tipPercent = p"
              >
                {{ p }}%
              </button>
            </div>
          </div>

          <div class="field">
            <label for="people">People</label>
            <div class="stepper">
              <button
                type="button"
                class="step"
                aria-label="Decrease people"
                :disabled="peopleValue <= 1"
                @click="changePeople(-1)"
              >−</button>
              <input
                id="people"
                v-model="people"
                type="number"
                inputmode="numeric"
                min="1"
                step="1"
                autocomplete="off"
              />
              <button
                type="button"
                class="step"
                aria-label="Increase people"
                @click="changePeople(1)"
              >+</button>
            </div>
          </div>

          <label class="check" for="round-up">
            <input id="round-up" v-model="roundUp" type="checkbox" />
            <span class="box" aria-hidden="true">
              <svg viewBox="0 0 16 16" width="12" height="12"><path d="M3 8.5l3 3 7-7" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round" /></svg>
            </span>
            <span class="check-text">
              <span class="check-label">Round up</span>
              <span class="check-hint">Total rounds up to the next whole dollar</span>
            </span>
          </label>

          <ul v-if="errors.length" class="errors" role="alert">
            <li v-for="e in errors" :key="e">{{ e }}</li>
          </ul>
        </form>

        <section class="results" aria-label="Results" aria-live="polite">
          <div class="row">
            <span class="label">Tip:</span>
            <output for="bill tip round-up" class="value">{{ fmt(tip) }}</output>
          </div>
          <div class="row">
            <span class="label">Total:</span>
            <output for="bill tip round-up" class="value">{{ fmt(total) }}</output>
          </div>
          <div class="row big">
            <span class="label">Per person:</span>
            <output for="bill tip people round-up" class="value">{{ fmt(perPerson) }}</output>
          </div>
          <p class="note" v-if="billValue === 0">Enter a bill amount to get started.</p>
          <p class="note" v-else>
            <template v-if="roundUp">
              Rounded up — effective tip {{ effectivePercent.toFixed(1) }}%,
            </template>
            <template v-else>{{ tipValue }}% tip,</template>
            split {{ peopleValue }} {{ peopleValue === 1 ? 'way' : 'ways' }}.
          </p>
          <button type="button" class="reset" @click="reset">Reset</button>
        </section>
      </div>
    </section>
  </main>
</template>

// integrations/harbor/tasks/tip-calculator-angular/steps/request/solution/app/src/app/app.ts
import { Component, computed, signal } from '@angular/core';

function toNumber(value: string): number {
  const n = parseFloat(value);
  return Number.isFinite(n) ? n : 0;
}

@Component({
  selector: 'app-root',
  template: `
    <main class="shell">
      <section class="card" aria-labelledby="title">
        <header class="head">
          <span class="logo" aria-hidden="true">🧾</span>
          <div>
            <h1 id="title">Tip calculator</h1>
            <p class="sub">Split the bill without the mental math.</p>
          </div>
        </header>

        <form class="fields" (submit)="$event.preventDefault()">
          <div class="field">
            <label for="bill">Bill amount</label>
            <div class="input-wrap">
              <span class="affix" aria-hidden="true">$</span>
              <input
                id="bill"
                type="number"
                inputmode="decimal"
                min="0"
                step="0.01"
                placeholder="0.00"
                [value]="bill()"
                (input)="bill.set(asValue($event))"
                [attr.aria-invalid]="billInvalid()"
              />
            </div>
            @if (billInvalid()) {
              <p class="error">Bill can't be negative.</p>
            }
          </div>

          <div class="field">
            <label for="tip">Tip percent</label>
            <div class="input-wrap">
              <input
                id="tip"
                type="number"
                inputmode="decimal"
                min="0"
                step="1"
                placeholder="0"
                [value]="tip()"
                (input)="tip.set(asValue($event))"
                [attr.aria-invalid]="tipInvalid()"
              />
              <span class="affix" aria-hidden="true">%</span>
            </div>
            <div class="presets" role="group" aria-label="Quick tip percentages">
              @for (p of presets; track p) {
                <button
                  type="button"
                  class="chip"
                  [class.active]="tipValue() === p"
                  [attr.aria-pressed]="tipValue() === p"
                  (click)="tip.set(p.toString())"
                >
                  {{ p }}%
                </button>
              }
            </div>
            @if (tipInvalid()) {
              <p class="error">Tip can't be negative.</p>
            }
          </div>

          <div class="field">
            <label for="people">People</label>
            <div class="stepper">
              <button type="button" class="step" aria-label="Fewer people" (click)="adjustPeople(-1)" [disabled]="peopleValue() <= 1">−</button>
              <input
                id="people"
                type="number"
                inputmode="numeric"
                min="1"
                step="1"
                [value]="people()"
                (input)="people.set(asValue($event))"
                [attr.aria-invalid]="peopleInvalid()"
              />
              <button type="button" class="step" aria-label="More people" (click)="adjustPeople(1)">+</button>
            </div>
            @if (peopleInvalid()) {
              <p class="error">Use a whole number of at least 1. Calculating for {{ peopleValue() }}.</p>
            }
          </div>
        </form>

        <section class="results" aria-live="polite" aria-label="Results">
          <p class="row">Tip: <strong>{{ money(tipAmount()) }}</strong></p>
          <p class="row">Total: <strong>{{ money(total()) }}</strong></p>
          <p class="row highlight">Per person: <strong>{{ money(perPerson()) }}</strong></p>
        </section>

        <button type="button" class="reset" (click)="reset()">Reset</button>
      </section>
    </main>
  `,
  styles: `
    .shell {
      min-height: 100vh;
      display: grid;
      place-items: center;
      padding: 24px 16px;
      box-sizing: border-box;
    }
    .card {
      width: 100%;
      max-width: 440px;
      background: var(--surface);
      border: 1px solid var(--border);
      border-radius: 18px;
      padding: 28px;
      box-shadow: 0 10px 30px rgb(0 0 0 / 0.08);
      box-sizing: border-box;
    }
    .head { display: flex; gap: 14px; align-items: center; margin-bottom: 24px; }
    .logo {
      font-size: 28px; width: 52px; height: 52px; display: grid; place-items: center;
      background: var(--accent-soft); border-radius: 14px; flex-shrink: 0;
    }
    h1 { margin: 0; font-size: 1.4rem; letter-spacing: -0.01em; }
    .sub { margin: 2px 0 0; color: var(--muted); font-size: 0.92rem; }
    .fields { display: grid; gap: 18px; }
    .field { display: grid; gap: 6px; }
    label { font-weight: 600; font-size: 0.9rem; }
    .input-wrap {
      display: flex; align-items: center; border: 1px solid var(--border);
      border-radius: 10px; background: var(--bg); padding: 0 12px;
      transition: border-color 0.15s, box-shadow 0.15s;
    }
    .input-wrap:focus-within {
      border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-soft);
    }
    .affix { color: var(--muted); font-weight: 600; }
    input {
      flex: 1; min-width: 0; border: none; background: transparent; color: inherit;
      font: inherit; font-size: 1.05rem; padding: 11px 8px; outline: none;
    }
    input[aria-invalid="true"] { color: var(--danger); }
    .presets { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 4px; }
    .chip {
      border: 1px solid var(--border); background: var(--bg); color: inherit;
      border-radius: 999px; padding: 6px 14px; font: inherit; font-size: 0.88rem;
      cursor: pointer; transition: background 0.15s, border-color 0.15s;
    }
    .chip:hover { border-color: var(--accent); }
    .chip.active { background: var(--accent); border-color: var(--accent); color: white; }
    .stepper {
      display: flex; align-items: center; border: 1px solid var(--border);
      border-radius: 10px; background: var(--bg); overflow: hidden;
    }
    .stepper:focus-within { border-color: var(--accent); box-shadow: 0 0 0 3px var(--accent-soft); }
    .stepper input { text-align: center; }
    .step {
      width: 46px; align-self: stretch; border: none; background: transparent;
      color: inherit; font-size: 1.3rem; cursor: pointer;
    }
    .step:hover:not(:disabled) { background: var(--accent-soft); }
    .step:disabled { opacity: 0.35; cursor: not-allowed; }
    button:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
    .error { margin: 0; color: var(--danger); font-size: 0.82rem; }
    .results {
      margin-top: 24px; padding: 16px 18px; border-radius: 14px;
      background: var(--accent-soft); display: grid; gap: 8px;
    }
    .row {
      margin: 0; display: flex; justify-content: space-between; gap: 12px;
      color: var(--muted); font-variant-numeric: tabular-nums;
    }
    .row strong { color: var(--text); font-size: 1.05rem; }
    .row.highlight { padding-top: 8px; border-top: 1px solid var(--border); }
    .row.highlight strong { color: var(--accent); font-size: 1.5rem; }
    .reset {
      margin-top: 16px; width: 100%; padding: 11px; border-radius: 10px;
      border: 1px solid var(--border); background: transparent; color: inherit;
      font: inherit; font-weight: 600; cursor: pointer;
    }
    .reset:hover { background: var(--accent-soft); border-color: var(--accent); }
    @media (max-width: 420px) {
      .card { padding: 20px; border-radius: 14px; }
    }
  `,
})
export class App {
  protected readonly presets = [10, 15, 18, 20, 25];

  protected readonly bill = signal('');
  protected readonly tip = signal('15');
  protected readonly people = signal('1');

  protected readonly billInvalid = computed(() => toNumber(this.bill()) < 0);
  protected readonly tipInvalid = computed(() => toNumber(this.tip()) < 0);
  protected readonly peopleInvalid = computed(() => {
    const raw = this.people().trim();
    if (raw === '') return false;
    const n = Number(raw);
    return !Number.isInteger(n) || n < 1;
  });

  protected readonly billValue = computed(() => Math.max(0, toNumber(this.bill())));
  protected readonly tipValue = computed(() => Math.max(0, toNumber(this.tip())));
  protected readonly peopleValue = computed(() => Math.max(1, Math.floor(toNumber(this.people()))));

  protected readonly tipAmount = computed(() => (this.billValue() * this.tipValue()) / 100);
  protected readonly total = computed(() => this.billValue() + this.tipAmount());
  protected readonly perPerson = computed(() => this.total() / this.peopleValue());

  protected asValue(event: Event): string {
    return (event.target as HTMLInputElement).value;
  }

  protected money(n: number): string {
    return '$' + (Math.round(n * 100) / 100).toFixed(2);
  }

  protected adjustPeople(delta: number): void {
    this.people.set(String(Math.max(1, this.peopleValue() + delta)));
  }

  protected reset(): void {
    this.bill.set('');
    this.tip.set('15');
    this.people.set('1');
  }
}
